feat: update cryptsetup to 2:2.8.7-1

diff --git a/tests/tcrypt-compat-test b/tests/tcrypt-compat-test
--- a/tests/tcrypt-compat-test
+++ b/tests/tcrypt-compat-test
@@ -10,6 +10,10 @@ PASSWORD="aaaaaaaaaaaa"
 PASSWORD_HIDDEN="bbbbbbbbbbbb"
 PASSWORD_72C="aaaaaaaaaaaabbbbbbbbbbbbccccccccccccddddddddddddeeeeeeeeeeeeffffffffffff"
 PIM=1234
+LOOP_SYS=""
+PART_IMG=tctst-part-img
+
+CRYPTOCHECK=./crypto-check
 
 if [ -n "$CRYPTSETUP_TESTS_RUN_IN_MESON" ]; then
 	CRYPTSETUP_VALGRIND=$CRYPTSETUP
@@ -20,15 +24,16 @@ fi
 
 [ -z "$srcdir" ] && srcdir="."
 
-function remove_mapping()
+remove_mapping()
 {
 	[ -b /dev/mapper/$MAP ] && dmsetup remove --retry $MAP
 	[ -b /dev/mapper/"$MAP"_1 ] && dmsetup remove --retry "$MAP"_1
 	[ -b /dev/mapper/"$MAP"_2 ] && dmsetup remove --retry "$MAP"_2
-	rm -rf $TST_DIR
+	[ -n "$LOOP_SYS" ] && losetup -d $LOOP_SYS
+	rm -rf $TST_DIR $PART_IMG
 }
 
-function fail()
+fail()
 {
 	[ -n "$1" ] && echo "$1"
 	echo " [FAILED]"
@@ -38,29 +43,31 @@ function fail()
 	exit 2
 }
 
-function skip()
+_sigchld() { local c=$?; [ $c -eq 139 ] && fail "Segfault"; [ $c -eq 134 ] && fail "Aborted"; }
+trap _sigchld CHLD
+
+skip()
 {
 	[ -n "$1" ] && echo "$1"
 	remove_mapping
 	exit 77
 }
 
-function test_one() # cipher mode keysize rm_pattern
+test_one() # cipher mode keysize rm_pattern
 {
-	$CRYPTSETUP benchmark -c "$1-$2" -s "$3" >/dev/null 2>&1
+	$CRYPTOCHECK cipher $1 $2 $3
 	if [ $? -ne 0 ] ; then
 		echo "$1-$2 [N/A]"
 		IMGS=$(ls $TST_DIR/[tv]c* | grep "$4")
 		[ -n "$IMGS" ] && rm $IMGS
-		#echo $IMGS
 	else
 		echo "$1-$2 [OK]"
 	fi
 }
 
-function test_kdf() # hash img_hash
+test_kdf() # hash img_hash
 {
-	$CRYPTSETUP benchmark -h "$1" >/dev/null 2>&1
+	$CRYPTOCHECK hash $1
 	if [ $? -ne 0 ] ; then
 		echo "pbkdf2-$1 [N/A]"
 		IMGS=$(ls $TST_DIR/[tv]c* | grep "$2")
@@ -70,16 +77,17 @@ function test_kdf() # hash img_hash
 	fi
 }
 
-function get_HASH_CIPHER() # filename
+get_HASH_CIPHER() # filename
 {
 	# speed up the test by limiting options for hash and (first) cipher
 	HASH=$(echo $file | cut -d'-' -f3)
 	CIPHER=$(echo $file | cut -d'-' -f5)
 }
 
-function test_required()
+test_required()
 {
 	command -v blkid >/dev/null || skip "blkid tool required, test skipped."
+	[ ! -x "$CRYPTOCHECK" ] && skip "Cannot find $CRYPTOCHECK, test skipped."
 
 	echo "REQUIRED KDF TEST"
 	test_kdf sha256      sha256
@@ -115,7 +123,13 @@ function test_required()
 	ls $TST_DIR/[tv]c* >/dev/null 2>&1 || skip "No remaining images, test skipped."
 }
 
-function valgrind_setup()
+check_uuid()
+{
+	UUID=$(blkid -p -o value -s UUID /dev/mapper/$MAP)
+	[ "$UUID" != "$1" ] && fail "UUID check failed."
+}
+
+valgrind_setup()
 {
 	command -v valgrind >/dev/null || fail "Cannot find valgrind."
 	[ ! -f $CRYPTSETUP_VALGRIND ] && fail "Unable to get location of cryptsetup executable."
@@ -125,7 +139,7 @@ function valgrind_setup()
 	fi
 }
 
-function valgrind_run()
+valgrind_run()
 {
 	INFOSTRING="$(basename ${BASH_SOURCE[1]})-line-${BASH_LINENO[0]}" ./valg.sh ${CRYPTSETUP_VALGRIND} "$@"
 }
@@ -184,7 +198,6 @@ for file in $(ls $TST_DIR/[tv]ck_*) ; do
 	echo " [OK]"
 done
 
-
 if [ $(id -u) != 0 ]; then
 	echo "WARNING: You must be root to run activation part of test, test skipped."
 	remove_mapping
@@ -192,23 +205,70 @@ if [ $(id -u) != 0 ]; then
 fi
 
 echo "ACTIVATION FS UUID CHECK"
-for file in $(ls $TST_DIR/[tv]c_* $TST_DIR/vcpim_* $TST_DIR/sys_[tv]c_*) ; do
+for file in $(ls $TST_DIR/[tv]c_* $TST_DIR/vcpim_*) ; do
 	echo -n " $file"
 	PIM_OPT=""
 	[[ $file =~ vcpim.* ]] && PIM_OPT="--veracrypt-pim $PIM"
-	SYS_OPT=""
-	[[ $file =~ sys_.* ]] && SYS_OPT="--tcrypt-system"
 	get_HASH_CIPHER $file
-	out=$(echo $PASSWORD | $CRYPTSETUP tcryptOpen $SYS_OPT $PIM_OPT -r -h $HASH -c $CIPHER $file $MAP 2>&1)
+	out=$(echo $PASSWORD | $CRYPTSETUP tcryptOpen $PIM_OPT -r -h $HASH -c $CIPHER $file $MAP 2>&1)
 	ret=$?
 	[ $ret -eq 1 ] && ( echo "$out" | grep -q -e "TCRYPT legacy mode" ) && echo " [N/A]" && continue
 	[ $ret -eq 1 ] && ( echo "$out" | grep -q -e "TCRYPT compatible mapping" ) && echo " [N/A]" && continue
 	[ $ret -ne 0 ] && fail
 	$CRYPTSETUP status $MAP >/dev/null || fail
 	$CRYPTSETUP status /dev/mapper/$MAP >/dev/null || fail
-	UUID=$(blkid -p -o value -s UUID /dev/mapper/$MAP)
-	$CRYPTSETUP remove $MAP || fail
-	[ "$UUID" != "DEAD-BABE" ] && fail "UUID check failed."
+	check_uuid DEAD-BABE
+	$CRYPTSETUP close $MAP || fail
+	echo " [OK]"
+done
+
+echo "ACTIVATION SYSTEM FS UUID CHECK"
+for file in $(ls $TST_DIR/sys_[tv]c_*) ; do
+	echo -n " $file"
+	LOOP_SYS=$(losetup -r -f --show -P $file)
+	if [ -z "$LOOP_SYS" ]; then
+		echo " [N/A]"
+		continue
+	fi
+	if [[ $file =~ _gpt_ ]]; then
+		LOOP_PART="$LOOP_SYS"p3
+	else
+		LOOP_PART="$LOOP_SYS"p1
+	fi
+	if [ ! -b "$LOOP_PART" ]; then
+		echo " [N/A]"
+		losetup -d $LOOP_SYS
+		LOOP_SYS=""
+		continue
+	fi
+	get_HASH_CIPHER $file
+	# map through partition name
+	echo -n " [PART]"
+	echo $PASSWORD | $CRYPTSETUP tcryptOpen --tcrypt-system -r -h $HASH -c $CIPHER $LOOP_PART $MAP || fail
+	check_uuid DEAD-BABE
+	$CRYPTSETUP close $MAP || fail
+	if [[ $file =~ _part ]]; then
+		# map through image only (TCRYPT hdr contains partition offset and size)
+		echo -n "[IMG]"
+		echo $PASSWORD | $CRYPTSETUP tcryptOpen --tcrypt-system -r -h $HASH -c $CIPHER $file $MAP 2>/dev/null || fail
+		check_uuid DEAD-BABE
+		$CRYPTSETUP close $MAP || fail
+		# map through full device (TCRYPT hdr contains partition offset and size)
+		echo -n "[DRIVE]"
+		echo $PASSWORD | $CRYPTSETUP tcryptOpen --tcrypt-system -r -h $HASH -c $CIPHER $LOOP_SYS $MAP || fail
+		check_uuid DEAD-BABE
+		$CRYPTSETUP close $MAP || fail
+	elif [[ $file =~ _full ]]; then
+		# map through image + header in real partition (whole system)
+		dd if=$LOOP_PART of=$PART_IMG bs=1M >/dev/null 2>&1
+		echo -n "[PART+IMG]"
+		echo $PASSWORD | $CRYPTSETUP tcryptOpen --tcrypt-system -r -h $HASH -c $CIPHER --header $LOOP_PART $PART_IMG $MAP || fail
+		check_uuid DEAD-BABE
+		$CRYPTSETUP close $MAP || fail
+		rm $PART_IMG
+	fi
+	losetup -d $LOOP_SYS
+	LOOP_SYS=""
 	echo " [OK]"
 done
 
@@ -221,9 +281,8 @@ for file in $(ls $TST_DIR/[tv]c_*-hidden) ; do
 	[ $ret -eq 1 ] && ( echo "$out" | grep -q -e "TCRYPT legacy mode" ) && echo " [N/A]" && continue
 	[ $ret -eq 1 ] && ( echo "$out" | grep -q -e "TCRYPT compatible mapping" ) && echo " [N/A]" && continue
 	[ $ret -ne 0 ] && fail
-	UUID=$(blkid -p -o value -s UUID /dev/mapper/$MAP)
-	$CRYPTSETUP remove $MAP || fail
-	[ "$UUID" != "CAFE-BABE" ] && fail "UUID check failed."
+	check_uuid CAFE-BABE
+	$CRYPTSETUP close $MAP || fail
 	echo " [OK]"
 done
 
